using FlashHttp.Abstractions;

namespace FlashHttp.Server;
internal partial class FlashHttpConnection
{
    private static readonly Dictionary<int, string> ReasonPhrases = new()
	{
		{ HttpStatusCodes.Status_100_Continue, "Continue" },
		{ HttpStatusCodes.Status_101_SwitchingProtocols, "Switching Protocols" },
		{ HttpStatusCodes.Status_102_Processing, "Processing" },
		{ HttpStatusCodes.Status_103_EarlyHints, "Early Hints" },
		{ HttpStatusCodes.Status_200_OK, "OK" },
		{ HttpStatusCodes.Status_201_Created, "Created" },
		{ HttpStatusCodes.Status_202_Accepted, "Accepted" },
		{ HttpStatusCodes.Status_203_NonAuthoritativeInformation, "Non-Authoritative Information" },
		{ HttpStatusCodes.Status_204_NoContent, "No Content" },
		{ HttpStatusCodes.Status_205_ResetContent, "Reset Content" },
		{ HttpStatusCodes.Status_206_PartialContent, "Partial Content" },
		{ HttpStatusCodes.Status_207_MultiStatus, "Multi-Status" },
		{ HttpStatusCodes.Status_208_AlreadyReported, "Already Reported" },
		{ HttpStatusCodes.Status_226_IMUsed, "IM Used" },
		{ HttpStatusCodes.Status_300_MultipleChoices, "Multiple Choices" },
		{ HttpStatusCodes.Status_301_MovedPermanently, "Moved Permanently" },
		{ HttpStatusCodes.Status_302_Found, "Found" },
		{ HttpStatusCodes.Status_303_SeeOther, "See Other" },
		{ HttpStatusCodes.Status_304_NotModified, "Not Modified" },
		{ HttpStatusCodes.Status_305_UseProxy, "Use Proxy" },
		{ HttpStatusCodes.Status_306_SwitchProxy, "Switch Proxy" },
		{ HttpStatusCodes.Status_307_TemporaryRedirect, "Temporary Redirect" },
		{ HttpStatusCodes.Status_308_PermanentRedirect, "Permanent Redirect" },
		{ HttpStatusCodes.Status_400_BadRequest, "Bad Request" },
		{ HttpStatusCodes.Status_401_Unauthorized, "Unauthorized" },
		{ HttpStatusCodes.Status_402_PaymentRequired, "Payment Required" },
		{ HttpStatusCodes.Status_403_Forbidden, "Forbidden" },
		{ HttpStatusCodes.Status_404_NotFound, "Not Found" },
		{ HttpStatusCodes.Status_405_MethodNotAllowed, "Method Not Allowed" },
		{ HttpStatusCodes.Status_406_NotAcceptable, "Not Acceptable" },
		{ HttpStatusCodes.Status_407_ProxyAuthenticationRequired, "Proxy Authentication Required" },
		{ HttpStatusCodes.Status_408_RequestTimeout, "Request Timeout" },
		{ HttpStatusCodes.Status_409_Conflict, "Conflict" },
		{ HttpStatusCodes.Status_410_Gone, "Gone" },
		{ HttpStatusCodes.Status_411_LengthRequired, "Length Required" },
		{ HttpStatusCodes.Status_412_PreconditionFailed, "Precondition Failed" },
		{ HttpStatusCodes.Status_413_ContentTooLarge, "Payload Too Large" },
		{ HttpStatusCodes.Status_414_URITooLong, "URI Too Long" },
		{ HttpStatusCodes.Status_415_UnsupportedMediaType, "Unsupported Media Type" },
		{ HttpStatusCodes.Status_416_RangeNotSatisfiable, "Range Not Satisfiable" },
		{ HttpStatusCodes.Status_417_ExpectationFailed, "Expectation Failed" },
		{ HttpStatusCodes.Status_418_ImATeapot, "I'm a teapot" },
		{ HttpStatusCodes.Status_421_MisdirectedRequest, "Misdirected Request" },
		{ HttpStatusCodes.Status_422_UnprocessableContent, "Unprocessable Entity" },
		{ HttpStatusCodes.Status_423_Locked, "Locked" },
		{ HttpStatusCodes.Status_424_FailedDependency, "Failed Dependency" },
		{ HttpStatusCodes.Status_425_TooEarly, "Too Early" },
		{ HttpStatusCodes.Status_426_UpgradeRequired, "Upgrade Required" },
		{ HttpStatusCodes.Status_428_PreconditionRequired, "Precondition Required" },
		{ HttpStatusCodes.Status_429_TooManyRequests, "Too Many Requests" },
		{ HttpStatusCodes.Status_431_RequestHeaderFieldsTooLarge, "Request Header Fields Too Large" },
		{ HttpStatusCodes.Status_451_UnavailableForLegalReasons, "Unavailable For Legal Reasons" },
		{ HttpStatusCodes.Status_500_InternalServerError, "Internal Server Error" },
		{ HttpStatusCodes.Status_501_NotImplemented, "Not Implemented" },
		{ HttpStatusCodes.Status_502_BadGateway, "Bad Gateway" },
		{ HttpStatusCodes.Status_503_ServiceUnavailable, "Service Unavailable" },
		{ HttpStatusCodes.Status_504_GatewayTimeout, "Gateway Timeout" },
		{ HttpStatusCodes.Status_505_HTTPVersionNotSupported, "HTTP Version Not Supported" },
		{ HttpStatusCodes.Status_506_VariantAlsoNegotiates, "Variant Also Negotiates" },
		{ HttpStatusCodes.Status_507_InsufficientStorage, "Insufficient Storage" },
		{ HttpStatusCodes.Status_508_LoopDetected, "Loop Detected" },
		{ HttpStatusCodes.Status_510_NotExtended, "Not Extended" },
		{ HttpStatusCodes.Status_511_NetworkAuthenticationRequired, "Network Authentication Required" }
	};

}
